### ISSUE TITLE
Add built_in_tag_id to output of get_receivers function

### ISSUE THREAD

**Issue by JolienGoossens** [inbo/etn#136]
In ETN database, the full tag ID (eg. A69-1601-60183) is added to receiver metadata (column (BUILT_IN_TAG_ID). Could this be added to the output of get_receivers()? 

(built_in_tag_fk is included in the output)

**Comment by peterdesmet** [comment]
Hi @JolienGoossens, I checked and the column `built_in_tag_id` is included in the output of `get_receivers()`, with `tag_id` values (e.g. `A69-1601-60511`). Can you:

1. Verify what version of the etn package you are using?
2. Give an example of where `tag_fk` is included rather than `tag_id`?

Thanks

**Comment by JolienGoossens** [comment]
Updated etn package and problem is indeed solved!
Thanks!
