### ISSUE TITLE
Extending etn package to retrieve cpod data

### ISSUE THREAD

**Issue by damianooldoni** [inbo/etn#79]
This issue discusses the enhancements proposed by user @DebusschereE about extending etn package to get cpod data, which are stored in etn database as well: http://www.lifewatch.be/etn/cpoddeployments.

Yes, this enhancement would be nice for sure. We have already some changes planned for the package as answer to some changes at db level. I will make my best to extend the package to cpod data as well before the "ETN training school" planned on 24 - 25 March 2020.

**Comment by peterdesmet** [comment]
Damiano, that seems (imo unrealistically) optimistic, but I love the optimism. 😄 More urgent are updating the pkg to the new view and the vignette.

**Comment by DebusschereE** [comment]
Beste Damiano, 
 
Ik zag onderstaand bericht van Peter Desmet en nu vroeg ik me af of het aanpassen van etn r pakket nog in je planning past? Er komen ook cpod users naar de etn workshop in maart, dus zou het heel leuk zijn dat dit op workshop komt; 
Volgens mij zijn de gevraagde toevoegingen niet veel werk zijn. Enkel de detections tab 'train analysis per minute' en 'train details' moeten toegevoegd worden met de correcte namen.

mvg,
Elisabeth

**Comment by peterdesmet** [comment]
Hi Elisabeth, if you reinstall the package (https://inbo.github.io/etn/#installation), you'll see that it is now possible to filter the data on `application_type="cpod"`, in the functions:

- `get_projects(application_type="cpod")`
- `get_deployments(application_type="cpod")`
- `get_receivers(application_type="cpod")`
- `get_detections(application_type="cpod")`

But the `get_detections()` function currently doesn't return any results, because it should be implemented on different views (train analysis per minute and train details), which we unfortunately won't be able to do before the training school.

**Comment by peterdesmet** [comment]
Closing this issue. As mentioned above, many functions now accept `application_type="cpod"`. But the main functionality (getting detections) is not yet possible, which is discussed in #105. @DebusschereE I suggest you subscribe to that issue to get updates.
